# Generated by Django 2.2.1 on 2020-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aspects',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
