# Generated by Django 2.2.1 on 2020-01-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200108_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
    ]
